"""Priority type corrected

Revision ID: 22ee4fe28e6e
Revises: 42ff7a9bf05e
Create Date: 2025-08-08 23:34:23.921961

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22ee4fe28e6e'
down_revision: Union[str, Sequence[str], None] = '42ff7a9bf05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE todo SET priority = 'NONE' WHERE priority IS NULL")
    op.execute("UPDATE todo SET priority = 'HIGH' WHERE priority = 'high'")
    op.execute("UPDATE todo SET priority = 'MEDIUM' WHERE priority = 'medium'")
    op.execute("UPDATE todo SET priority = 'LOW' WHERE priority = 'low'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE todo SET priority = NULL WHERE priority = 'NONE'")
    op.execute("UPDATE todo SET priority = 'high' WHERE priority = 'HIGH'")
    op.execute("UPDATE todo SET priority = 'medium' WHERE priority = 'MEDIUM'")
    op.execute("UPDATE todo SET priority = 'low' WHERE priority = 'LOW'")
    # ### end Alembic commands ###
