"""Added priority, createdAt, completedAt

Revision ID: 42ff7a9bf05e
Revises: 
Create Date: 2025-08-07 20:11:53.464959

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ff7a9bf05e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('todo', sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False, server_default=datetime.now(timezone.utc).isoformat(sep=' ', timespec='seconds')))
    op.add_column('todo', sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completedAt')
    op.drop_column('todo', 'createdAt')
    op.drop_column('todo', 'priority')
    # ### end Alembic commands ###
