"""Difficulty and dueDate added

Revision ID: b3508588f2f7
Revises: 6ddfcc4cec89
Create Date: 2025-08-14 14:46:52.501835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3508588f2f7'
down_revision: Union[str, Sequence[str], None] = '6ddfcc4cec89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('todo', sa.Column('dueDate', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'dueDate')
    op.drop_column('todo', 'difficulty')
    # ### end Alembic commands ###
